/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InfoList.java
 *
 * Created on 06/12/2010, 18:46:41
 */
package com.geral;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rudieri T. Colbek
 */
public class InfoList extends javax.swing.JDialog {

    DefaultTableModel dftm;

    /** Creates new form InfoList */
    public InfoList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dftm = (DefaultTableModel) jTable1.getModel();
        dftm.setRowCount(0);
    }

    public void add(String chave, String valor) {
        Object[] linha = new Object[2];
        linha[0] = chave;
        linha[1] = valor;
        int indice=indexOf(chave);
        if (indice==-1) {
           dftm.setValueAt(valor, indice, 1);
        }
        dftm.addRow(linha);
    }

    public int indexOf(String chave) {
        for (int i = 0; i < dftm.getRowCount(); i++) {
            Object ob = dftm.getValueAt(i, 0);
            if (ob != null) {

                if (ob.toString().equals(chave)) {
                    return i;
                }
            }
        }
        return -1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel5);

        jButton1.setText("Fechar");
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                InfoList dialog = new InfoList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
