DROP table IF EXISTS playmusica cascade;

CREATE TABLE playmusica(
id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
playlist SMALLINT NOT NULL
foreign key references PLAYLIST(id),
musica SMALLINT NOT NULL
foreign key references MUSICA(id),
seq smallint);

