/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JConfiguracao.java
 *
 * Created on 19/08/2010, 21:17:54
 */

package com.configuracao;

import java.util.HashMap;
import java.util.Set;

/**
 *
 * @author manchini
 */
public class JConfiguracao extends javax.swing.JDialog {

    /** Creates new form JConfiguracao */
    public JConfiguracao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTela();
    }

    private void setTela(){
        try {
           HashMap<String,String> lista = ConfiguracaoBD.listar(new ConfiguracaoSC());
           jCheckBox_teste.setSelected(lista.get("teste") == null?false:Boolean.parseBoolean(lista.get("teste").toString()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setDadosBanco(){
        HashMap<String,String> lista = new HashMap<String, String>();
        lista.put("teste", String.valueOf(jCheckBox_teste.isSelected()));

        Set chaves = lista.keySet();
        for(int i =0; i < chaves.toArray().length;i++){
            try{
            Configuracao conf = new Configuracao();
            conf.setChave(chaves.toArray()[i].toString());
            Boolean existe = ConfiguracaoBD.carregar(conf);
            conf.setValor(lista.get(chaves.toArray()[i]));
            if(existe){
                ConfiguracaoBD.alterar(conf);
            }else{
                ConfiguracaoBD.incluir(conf);
            }

            }catch(Exception ex){
                System.out.println("Erro ao Salvar Configuracao");
                ex.printStackTrace();
            }

        }

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Geral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox_teste = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel_Avancada = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel_Avancada1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel_Avancada2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(441, 342));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 25));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel2.setText("Configurações");
        jPanel4.add(jLabel2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel_Geral.setLayout(new javax.swing.BoxLayout(jPanel_Geral, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Teste:");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 17));
        jPanel2.add(jLabel1);
        jPanel2.add(jCheckBox_teste);

        jPanel_Geral.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel_Geral.add(jPanel3);

        jTabbedPane1.addTab("Geral", jPanel_Geral);

        jPanel_Avancada.setLayout(new javax.swing.BoxLayout(jPanel_Avancada, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Avançado:");
        jPanel5.add(jLabel3);

        jPanel_Avancada.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel_Avancada.add(jPanel6);

        jTabbedPane1.addTab("Avançada", jPanel_Avancada);

        jPanel_Avancada1.setLayout(new javax.swing.BoxLayout(jPanel_Avancada1, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Avançado:");
        jPanel7.add(jLabel4);

        jPanel_Avancada1.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel_Avancada1.add(jPanel8);

        jTabbedPane1.addTab("Fodastica", jPanel_Avancada1);

        jPanel_Avancada2.setLayout(new javax.swing.BoxLayout(jPanel_Avancada2, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Avançado:");
        jPanel9.add(jLabel5);

        jPanel_Avancada2.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel_Avancada2.add(jPanel10);

        jTabbedPane1.addTab("Oo'", jPanel_Avancada2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 35));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1);

        getContentPane().add(jPanel11, java.awt.BorderLayout.PAGE_END);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-443)/2, (screenSize.height-374)/2, 443, 374);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setDadosBanco();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setDadosBanco();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JConfiguracao dialog = new JConfiguracao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_teste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Avancada;
    private javax.swing.JPanel jPanel_Avancada1;
    private javax.swing.JPanel jPanel_Avancada2;
    private javax.swing.JPanel jPanel_Geral;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
