/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_gtk_NativeGtkSystemTray */

#ifndef _Included_com_utils_gtk_NativeGtkSystemTray
#define _Included_com_utils_gtk_NativeGtkSystemTray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utils_gtk_NativeGtkSystemTray
 * Method:    addMenuItem
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_utils_gtk_NativeGtkSystemTray_addMenuItem
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
