/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utils.pele;

import com.main.Carregador;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author rudieri
 */
public class JPele extends javax.swing.JDialog {

    /**
     * Creates new form JPele
     */
    private JSelecionaCor jSelecionaCor;
    private JLabel componenteSelecionado;
    private DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
    private final Carregador carregador;

    public JPele(Carregador carregador) {
        initComponents();
        jSelecionaCor = new JSelecionaCor(null, false);
        jSelecionaCor.addCorSelecionadaListener(new CorSelecionadaListener() {
            @Override
            public void corSelecionada(Color cor) {
                if (componenteSelecionado == null) {
                    throw new IllegalStateException("O componente selecionado não pode ser nulo.");
                }
                componenteSelecionado.setBackground(cor);
            }
        });
        this.carregador = carregador;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        try {
            defaultComboBoxModel.removeAllElements();
            for (int i = 0; i < ColorUtils.getListaPelesConhecidas().size(); i++) {
                Pele pele = ColorUtils.getListaPelesConhecidas().get(i);
                defaultComboBoxModel.addElement(pele.getNome());
            }
            jComboBox1.setModel(defaultComboBoxModel);
            jComboBox1.setSelectedItem(ColorUtils.getPeleAtual().getNome());
            setPele(ColorUtils.getPeleAtual());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void selecionarCor(Object source) {
        componenteSelecionado = (JLabel) source;
        jSelecionaCor.setVisible(true);
    }

    private void setPele(Pele pele) {
        jPanelEditarCores.setVisible(pele != Pele.PELE_PADRAO);
        jLabelCorFundoObjetos.setBackground(pele.getFundoTabelaNaoSelecionada());
        jLabelCorFundoSelecionado.setBackground(pele.getFundoTabelaSelecionada());
        jLabelCorTextoObjetos.setBackground(pele.getFrenteTabelaNaoSelecionada());
        jLabelCorTextoSelecionado.setBackground(pele.getFrenteTabelaSelecionada());
        jLabelCorFundoJanela.setBackground(pele.getFundoJanela());
        jLabelCorFundoJanela.setBorder(new BevelBorder(BevelBorder.LOWERED, ColorUtils.getFrenteJanela(), ColorUtils.getFrenteJanela()));
        jLabelCorTextoJanela.setBackground(pele.getFrenteJanela());
        jLabelCorTextoJanela.setBorder(new BevelBorder(BevelBorder.LOWERED, ColorUtils.getFundoJanela(), ColorUtils.getFundoJanela()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanelEditarCores = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCorFundoJanela = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCorTextoJanela = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCorFundoSelecionado = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCorTextoSelecionado = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelCorFundoObjetos = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCorTextoObjetos = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("Tema: ");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel5.add(jLabel7);

        jComboBox1.setEditable(true);
        jComboBox1.setPreferredSize(new java.awt.Dimension(200, 26));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel5.add(jComboBox1);

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanelEditarCores.setLayout(new javax.swing.BoxLayout(jPanelEditarCores, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Fundo Janelas:");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel4.add(jLabel1);

        jLabelCorFundoJanela.setBackground(new java.awt.Color(1, 1, 1));
        jLabelCorFundoJanela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorFundoJanela.setOpaque(true);
        jLabelCorFundoJanela.setPreferredSize(new java.awt.Dimension(22, 20));
        jLabelCorFundoJanela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorFundoJanelaMouseClicked(evt);
            }
        });
        jPanel4.add(jLabelCorFundoJanela);

        jPanelEditarCores.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Texto Janelas:");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel6.add(jLabel2);

        jLabelCorTextoJanela.setBackground(new java.awt.Color(1, 1, 1));
        jLabelCorTextoJanela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorTextoJanela.setOpaque(true);
        jLabelCorTextoJanela.setPreferredSize(new java.awt.Dimension(22, 20));
        jLabelCorTextoJanela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorTextoJanelaMouseClicked(evt);
            }
        });
        jPanel6.add(jLabelCorTextoJanela);

        jPanelEditarCores.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Fundo Selecionado:");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel7.add(jLabel3);

        jLabelCorFundoSelecionado.setBackground(new java.awt.Color(1, 1, 1));
        jLabelCorFundoSelecionado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorFundoSelecionado.setOpaque(true);
        jLabelCorFundoSelecionado.setPreferredSize(new java.awt.Dimension(22, 20));
        jLabelCorFundoSelecionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorFundoSelecionadoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelCorFundoSelecionado);

        jPanelEditarCores.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Texto Selecionado:");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel8.add(jLabel4);

        jLabelCorTextoSelecionado.setBackground(new java.awt.Color(1, 1, 1));
        jLabelCorTextoSelecionado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorTextoSelecionado.setOpaque(true);
        jLabelCorTextoSelecionado.setPreferredSize(new java.awt.Dimension(22, 20));
        jLabelCorTextoSelecionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorTextoSelecionadoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelCorTextoSelecionado);

        jPanelEditarCores.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Fundo Objetos:");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel9.add(jLabel5);

        jLabelCorFundoObjetos.setBackground(new java.awt.Color(1, 1, 1));
        jLabelCorFundoObjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorFundoObjetos.setOpaque(true);
        jLabelCorFundoObjetos.setPreferredSize(new java.awt.Dimension(22, 20));
        jLabelCorFundoObjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorFundoObjetosMouseClicked(evt);
            }
        });
        jPanel9.add(jLabelCorFundoObjetos);

        jPanelEditarCores.add(jPanel9);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("Texto Objetos:");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel11.add(jLabel6);

        jLabelCorTextoObjetos.setBackground(new java.awt.Color(1, 1, 1));
        jLabelCorTextoObjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorTextoObjetos.setOpaque(true);
        jLabelCorTextoObjetos.setPreferredSize(new java.awt.Dimension(22, 20));
        jLabelCorTextoObjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorTextoObjetosMouseClicked(evt);
            }
        });
        jPanel11.add(jLabelCorTextoObjetos);

        jPanelEditarCores.add(jPanel11);

        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanelEditarCores.add(jPanel10);

        jPanel1.add(jPanelEditarCores, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCorFundoJanelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorFundoJanelaMouseClicked
        selecionarCor(evt.getSource());
    }//GEN-LAST:event_jLabelCorFundoJanelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ColorUtils.setNomePele(jComboBox1.getSelectedItem().toString());
        ColorUtils.setFrenteTabelaSelecionada(jLabelCorTextoSelecionado.getBackground());
        ColorUtils.setFrenteTabelaNaoSelecionada(jLabelCorTextoObjetos.getBackground());
        ColorUtils.setFundoTabelaSelecionada(jLabelCorFundoSelecionado.getBackground());
        ColorUtils.setFundoTabelaNaoSelecionada(jLabelCorFundoObjetos.getBackground());
        ColorUtils.setFrenteJanela(jLabelCorTextoJanela.getBackground());
        ColorUtils.setFundoJanela(jLabelCorFundoJanela.getBackground());
        ColorUtils.aplicarTema();
        if (ColorUtils.getPeleAtual() == Pele.PELE_PADRAO) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "O Crepz deve ser reiniciado.\nDeseja fechá-lo agora?", "Fechar crepz...", JOptionPane.YES_NO_OPTION);
            if (showConfirmDialog == JOptionPane.YES_OPTION) {
                carregador.sair();
            }
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelCorTextoJanelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorTextoJanelaMouseClicked
        selecionarCor(evt.getSource());
    }//GEN-LAST:event_jLabelCorTextoJanelaMouseClicked

    private void jLabelCorFundoSelecionadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorFundoSelecionadoMouseClicked
        selecionarCor(evt.getSource());
    }//GEN-LAST:event_jLabelCorFundoSelecionadoMouseClicked

    private void jLabelCorTextoSelecionadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorTextoSelecionadoMouseClicked
        selecionarCor(evt.getSource());
    }//GEN-LAST:event_jLabelCorTextoSelecionadoMouseClicked

    private void jLabelCorFundoObjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorFundoObjetosMouseClicked
        selecionarCor(evt.getSource());
    }//GEN-LAST:event_jLabelCorFundoObjetosMouseClicked

    private void jLabelCorTextoObjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorTextoObjetosMouseClicked
        selecionarCor(evt.getSource());
    }//GEN-LAST:event_jLabelCorTextoObjetosMouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Pele pele = ColorUtils.getPelePorNome(evt.getItem().toString());
            if (pele == null) {
                pele = new Pele(jComboBox1.getSelectedItem().toString());
            }
            setPele(pele);
        }


    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Pele pele = ColorUtils.getPelePorNome(jComboBox1.getSelectedItem().toString());
            if (pele == null) {
                pele = new Pele(jComboBox1.getSelectedItem().toString());
            }
            setPele(pele);
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pele pele = new Pele("Novo...");
        jComboBox1.addItem(pele.getNome());
        jComboBox1.setSelectedItem(pele.getNome());
        setPele(pele);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JPele dialog = new JPele(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCorFundoJanela;
    private javax.swing.JLabel jLabelCorFundoObjetos;
    private javax.swing.JLabel jLabelCorFundoSelecionado;
    private javax.swing.JLabel jLabelCorTextoJanela;
    private javax.swing.JLabel jLabelCorTextoObjetos;
    private javax.swing.JLabel jLabelCorTextoSelecionado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelEditarCores;
    // End of variables declaration//GEN-END:variables
}
