/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JLista.java
 *
 * Created on 16/06/2010, 14:39:00
 */

package com.playlist;

/**
 *
 * @author Rudieri T. Colbek
 */
public class JLista extends javax.swing.JPanel {

    /** Creates new form JLista */
    public JLista(String n, String a) {
       

        initComponents();
        jLabel1.setText(n);
         jLabel2.setText(a);

        
    }

    @Override
    public void setOpaque(boolean isOpaque) {
        if(jLabel1!=null)
        jLabel1.setOpaque(isOpaque);
        if(jLabel2!=null)
        jLabel2.setOpaque(isOpaque);
        super.setOpaque(isOpaque);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 146, 54));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.black, java.awt.Color.black)));
        setForeground(new java.awt.Color(0, 0, 204));
        setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setBackground(new java.awt.Color(238, 146, 54));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 45, 31));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nome da musica (se não tiver, aparece o nome do arquivo)");
        add(jLabel1);

        jLabel2.setBackground(new java.awt.Color(238, 146, 54));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel2.setText("Artista que fez ou gravou a musica XD");
        add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
